namespace Magpie {
	delegate void SignalDelegate();
}

#include "RootPage.idl"

namespace Magpie {
	[default_interface]
	runtimeclass App : Windows.UI.Xaml.Application {
		static Windows.Globalization.NumberFormatting.INumberFormatter2 DoubleFormatter { get; };
	}
}
