namespace Magpie {
	delegate void SignalDelegate();
}

#include "CaptionButtonsControl.idl"
#include "TitleBarControl.idl"
#include "PageFrame.idl"
#include "RootPage.idl"
#include "HomePage.idl"

namespace Magpie {
	[default_interface]
	runtimeclass App : Windows.UI.Xaml.Application {
		static Windows.Globalization.NumberFormatting.INumberFormatter2 DoubleFormatter { get; };
	}
}
